name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main # When there is anytime a push to the master branch then run the below build and push jobs....

jobs:
  build-and-push:
    runs-on: ubuntu-latest # It runs on a ubuntu machine.....
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2 # It checks out  the code base....

      - name: Log in to Docker Hub # It logins to the docker hub with the below "docker/login-action@v1"
        uses: docker/login-action@v1 # This is something which is provided by the docker....
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # These both will come from the github secrets
          password: ${{ secrets.DOCKER_PASSWORD }} # These both will come from the github secrets....

      - name: Build and Push Docker image # Here build and push of the docker image happens with the below "docker/build-push-action@v2"
        uses: docker/build-push-action@v2 # This is something which is provided by the docker....
        with:
          context: . # Here the context is coming from the root folder...
          file: ./docker/Dockerfile.user
          push: true
          tags: muraliju981108/paytm-deploy # Replace with your Docker Hub username and repository

      - name: Verify Pushed Image
        run: docker pull 100xdevs/week-18-class:latest # Replace with your Docker Hub username and repository

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull 100xdevs/week-18-class:latest
            sudo docker stop web-app || true
            sudo docker rm web-app || true
            sudo docker run -d --name web-app -p 3005:3000 100xdevs/week-18-class:latest
